g2: simplify g2_msg_log_dropped_pmsg() and g2_msg_log_dropped_data()
This commit simplify g2_msg_log_dropped_pmsg() and
g2_msg_log_dropped_data(), dropping the fmt==NULL branch.

This check is anyway later performed by g2_msg_log_dropped(),
and passing NULL as va_list argument breaks on ARM:

"""
msg.c: In function 'g2_msg_log_dropped_pmsg':
msg.c:477:3: error: incompatible type for argument 4 of 'g2_msg_log_dropped'
   g2_msg_log_dropped(pmsg_start(mb), pmsg_size(mb), NULL, NULL);
   ^
msg.c:449:1: note: expected 'va_list' but argument is of type 'void *'
 g2_msg_log_dropped(const void *data, size_t len, const char *fmt, va_list args)
 ^
msg.c: In function 'g2_msg_log_dropped_data':
msg.c:493:3: error: incompatible type for argument 4 of 'g2_msg_log_dropped'
   g2_msg_log_dropped(data, len, NULL, NULL);
   ^
msg.c:449:1: note: expected 'va_list' but argument is of type 'void *'
 g2_msg_log_dropped(const void *data, size_t len, const char *fmt, va_list args)
"""

Signed-off-by: Luca Bruno <lucab@debian.org>